spring:
  cloud:
    gateway:
      routes:
      - id: dream-cloud-authority
        uri: lb://DREAM-CLOUD-HOME
        predicates:
          - Path=/home/**
        filters:
          - StripPrefix=1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dream_cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    druid:
      # 初始连接数
      initial-size: 10
      # 最大连接池数量
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
          enabled: true
          url-pattern: /monitor/druid/*
      filter:
          stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: false
          wall:
              config:
                  multi-statement-allow: true

logging:
  level:
    org.springframework.cloud.gateway: debug

app:
  access-control:
    premit-all:
    - {urls:["/test1/**","/user/**"]}
    has-any-role:
    - {urls:["/test2/**"],roles:["ADMIN","SUPER"]}
    web-ignoring:
    - {urls:["/**/public/**"]}
  jwtSecret: xxxx
  jwtExpirationDay: 30

mybatis:
  mapper-locations: classpath:mapper/*.xml


jwt:

